### ISSUE TITLE
Требую поем эмодзи

### ISSUE THREAD

**Issue by chebupelka10** [HotDrify/teagram#11]
Эта ёбанная бедность...

**Comment by mrksbgg** [comment]
[https://www.youtube.com/watch?v=CyPhiMdG3sw](url)

**Comment by chebupelka10** [comment]
И мне пришлось принимать третье джакузи за день...

**Comment by itzlayz** [comment]
нахуя сюда делать исусы, репо не обновляется

**Comment by HotDrify** [comment]
@itzlayz ав че, ахуели, забаню нахуй щас
